### ISSUE TITLE
model file

### ISSUE THREAD

**Issue by Tawannaer** [iMED-Lab/COSTA#2]
Thank you very much for sharing this project. Your workflow is well-established and you have proposed a very interesting network, which I believe is a advancement in the field of vessel segmentation. Could you please share your network structure code? I only want to reproduce the code for basic research.Thank you again, and I look forward to your reply.

**Comment by iBrain-007** [comment]
Hi @Tawannaer 

Thank you for expressing interest in our work. The network structure code for this project will be made available upon acceptance of the manuscript. Thank you!

Best,
COSTA
